version: '3.8'

services:
  postgres-auth:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        postgres-auth:
          condition: service_healthy
      links:
        - postgres-auth
